# Configuración general
name: 'Proyecto' # ¡Pon el nombre de tu proyecto aquí!
version: '1.0.0'
config-version: 2

profile: 'default'

# Rutas de carpetas
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"] # Vital para el SCD2

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Enrutamiento y Materialización
models:
  Proyecto: # ¡Pon el nombre de tu proyecto aquí también!
    
    # Capa Silver (Vistas ligeras por defecto)
    staging:
      +schema: silver
      +materialized: view 
      
    # Capa Gold (Tablas físicas para PowerBI/Tableau)
    marts:
      +schema: gold
      dims:
        +materialized: table
      facts:
        +materialized: table