name: 'pkdd99_credit_risk'
version: '1.0.0'
config-version: 2

# /.dbt/profiles.yml
profile: 'pkdd99_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  pkdd99_credit_risk: 
    
    bronze:
      +schema: bronze
      +materialized: view
      +tags: ["bronze"]

    staging:
      +schema: silver
      +materialized: table
      +tags: ["silver"]

    marts:
      core:
        +schema: gold
        +materialized: table
        +tags: ["gold", "core"]
      risk:
        +schema: gold
        +materialized: table
        +tags: ["gold", "risk"]
      analytics:
        +schema: analytics
        +materialized: table
        +tags: ["gold", "ml_features"]

# Configuración para la carga de CSVs estáticos
seeds:
  pkdd99_credit_risk:
    +schema: silver
    +tags: ["seed", "dictionary"]