# Nombre descriptivo y profesional del proyecto
name: 'pkdd99_credit_risk'
version: '1.0.0'
config-version: 2

# El perfil debe coincidir con el que definas en tu ~/.dbt/profiles.yml
profile: 'pkdd99_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

# Configuración centralizada de modelos (Arquitectura Medallion)
models:
  pkdd99_credit_risk: # <--- OBLIGATORIO: Debe ser idéntico al 'name:' de arriba
    
    # Capa Bronze: Vistas ligeras directamente contra la raw data
    bronze:
      +schema: bronze
      +materialized: view
      +tags: ["bronze"]

    # Capa Silver (Staging): Limpieza y normalización
    staging:
      +schema: silver
      +materialized: table
      +tags: ["silver"]

    # Capa Gold (Marts): Modelado dimensional y Features para ML
    marts:
      core:
        +schema: gold
        +materialized: table
        +tags: ["gold", "core"]
      analytics:
        +schema: analytics
        +materialized: table
        +tags: ["gold", "ml_features"]

# Configuración para la carga de CSVs estáticos
seeds:
  pkdd99_credit_risk:
    +schema: silver
    +tags: ["seed", "dictionary"]